version: "3"
services:
    rabbit:
        image: rabbitmq:3-management
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - "5672:5672"
            - "15672:15672"
    
    publisher:
        build: ./publisher-service
        image: abaig316/docker-getting-started-publisher-service
        environment:
            - RABBIT_HOST=amqp://rabbit
        
    consumer:
        build: ./consumer-service
        image: abaig316/docker-getting-started-consumer-service
        ports:
            - "3000:3000"
        environment:
            - RABBIT_HOST=amqp://rabbit
