apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbit
spec:
    selector:
        matchLabels:
            app: rabbit
    template:
        metadata:
            labels:
                app: rabbit
        spec:
            containers:
            - name: rabbit
              image: rabbitmq:3-management
              ports:
              - containerPort: 5672
                name: amqp-port
              - containerPort: 15672
                name: console-port
              livenessProbe:
                tcpSocket:
                    port: 5672
                initialDelaySeconds: 5
                timeoutSeconds: 10