apiVersion: v1
kind: Service
metadata:
    name: rabbit
spec:
    selector:
        app: rabbit
    ports:
    - port: 5672
      name: amqp
      targetPort: amqp-port
      protocol: TCP
    - port: 15672
      name: console
      targetPort: console-port
      protocol: TCP