apiVersion: v1
kind: Service
metadata:
    name: consumer
spec:
    selector:
        app: consumer
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
      protocol: TCP